### ISSUE TITLE
Handle MC URLs with alternate JSON formatting

### ISSUE THREAD

**Issue by CrisNelson** [globalvoices/NewsFrames-Code#28]

**Comment by scttnlsn** [comment]
PR opened here: https://github.com/globalvoices/NewsFrames-Code/pull/29

The solution is not great and should be removed as soon as this is fixed in Media Cloud.

**Comment by CrisNelson** [comment]
Test normal expected URLs, just a bunch of MC entries.

**Comment by shrutimehta13** [comment]
MC search is not working. Following is the observation.

search Term and query URL from logged in user of MC is giving proper error - media cloud not responding
MC query URLs (without login) like https://explorer.mediacloud.org/#/queries/demo/search?q=[{"q":"football%202018"}]&auto=true  give unexpected error time 9:15pm-9:30pm IST

<img width="1323" alt="screen shot 2018-06-17 at 9 14 50 pm" src="https://user-images.githubusercontent.com/34771314/41509739-315322c2-7276-11e8-92a7-90262f3790bc.png">

**Comment by connieimdialog** [comment]
- the original issue works.  that's fixed
-- shruti, that URL is from the demo, and demo URLs aren't really the "real ones", so that's why it doesn't work.  but we should be clearer somewhere about that, so i updated the .yml instruction in the develop branch
-- ran across another issue created by the JSON, where the 'linefeed' character got added by accidentally hitting "return" in the Media Cloud textbox (https://explorer.mediacloud.org/#/queries/search?q=[{%22label%22:%22migration%22,%22q%22:%22migration%0A%22,%22color%22:%22%231f77b4%22,%22startDate%22:%222018-05-25%22,%22endDate%22:%222018-06-25%22,%22sources%22:[],%22collections%22:[9272347]}]).  but we can't fix 'em all. so let's consider this closed.
